#!/bin/sh
set -ex
rm -rf mkall.framework
baseurl="https://github.com/measurement-kit/mkall-ios"
v=`cat VERSION`
curl -fsSLO "$baseurl/releases/download/v${v}/mkall-${v}.framework.tgz"
expsum=`cat SHA256SUM`
realsum=`shasum -a 256 mkall-${v}.framework.tgz | awk '{print $1}'`
if [ "$expsum" != "$realsum" ]; then
  echo "FATAL: invalid framework checksum" 1>&2
  exit 1
fi
tar -xzf mkall-${v}.framework.tgz
