#!/bin/sh
set -ex
v=`cat VERSION`
tarball=mkall-${v}.framework.tgz
(
  set -ex
  cd Carthage/Build/iOS/
  tar -czf ../../../${tarball} mkall.framework
)
shasum -a 256 ${tarball} | awk '{print $1}' > SHA256SUM
